import React from "react";
import "./DetailServices.css";

import { FaAngleRight } from "react-icons/fa6";
import { motion } from "framer-motion";
import { IoMdCheckmarkCircleOutline } from "react-icons/io";
import { GiStarShuriken } from "react-icons/gi";
import { container, featureVariantsAbout } from "../../data/animation";
import { Link } from "react-router-dom";
// import { IoMdCheckmarkCircleOutline } from "react-icons/io";
// import { GiStarShuriken } from "react-icons/gi";
// import { featureVariantsAbout } from "../../data/animation";
const transition = { type: "spring", duration: 1 };
export const DetailServices = () => {
  return (
    <div className="detail-section-card">
      <div className="our-stories-first-card">
        <div className="our-stories-first-card-inner-card">
          <div className="our-stories-fisrt-card-our-story-text">
            {/* <span></span> */}
            <h3>Nuhvin Services</h3>
          </div>
          <h1>What we say to Our people</h1>
          <p>
            comprehensive design, cutting-edge AI, and digital solutions that
            help businesses succeed from startup to enterprise.
          </p>
        </div>
        <motion.div
          initial={{ x: -100 }}
          whileInView={{ x: 0 }}
          transition={transition}
          className="our-stories-left-side-image-card"
        >
          <img src="/images/our-story-left.jpg" alt="our-story-left" />
          <motion.div
            // initial={{ rotate: 45 }}
            // whileInView={{ rotate: 0 }}
            // transition={{ duration: 2.5, type: "spring" }}
            initial={{ rotate: 0 }}
            animate={{ rotate: 360 }}
            transition={{ duration: 18, repeat: Infinity, ease: "linear" }}
            className="our-story-left-side-dotted-card"
          >
            <span className="our-story-left-side-dotted-first-big-dot"></span>
          </motion.div>
        </motion.div>
        <motion.div
          initial={{ x: 100 }}
          whileInView={{ x: 0 }}
          transition={{ ...transition, duration: 2 }}
          className="our-stories-right-side-image-card"
        >
          <img src="/images/5ac603279f.jpg" alt="" />
          <div className="our-stories-right-side-dotted-card"></div>
        </motion.div>
      </div>

      <div className="our-stories-second-card">
        <h2>
          We <span className="shero-span-color">Meet</span> you right where you
          are
        </h2>
        <p>
          Together, we develop patented technology that is really intelligent,
        </p>
        <p>
          AI-based, and cognitive.So much so that we can automate sophisticated,
          mission-critical procedures .
        </p>
        <p>
          This IQ was generated by our humans via the care of the clients and
        </p>
        <p>
          We can unleash creativity, optimize productivity, and accelerate your
          growth in this way.And never stop inventing
        </p>
        <p>to create amazing experiences that will pleasure us tomorrow.</p>
        <button>Nuhvin Info</button>
      </div>

      <div className="all-services-main-card">
        <div className="all-services-main-first-card">
          <p>//OUR SERVICES</p>
          <h2>We Run All Kinds Of Services In Form Of</h2>
          <h1>
            Information & <span className="shero-span-color">Technologies</span>
          </h1>
        </div>
        <div className="all-services-each-card">
          {/* ai */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Artificial Intelligence(AI)</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link to="/ai" className="detail-service-link new-serv-link">
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>01</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_UI_UX.png"
              alt=""
            />
          </motion.div>
          {/* cloud */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Cybersecurity</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link
              to="/cloud-computing-details"
              className="detail-service-link new-serv-link"
            >
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>01</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_UI_UX.png"
              alt=""
            />
          </motion.div>
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Ui/Ux Design</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link className="detail-service-link new-serv-link">
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>01</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_UI_UX.png"
              alt=""
            />
          </motion.div>
          {/* Software development */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0.1)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Software Development</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link
              className="detail-service-link new-serv-link"
              to="/software-developemnt-details"
            >
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>02</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_software development.png"
              alt=""
            />
          </motion.div>
          {/* Web development */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0.2)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Web Development</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link
              className="detail-service-link new-serv-link"
              to="/web-details"
            >
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>03</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services _web development.png"
              alt=""
            />
          </motion.div>
          {/* Mobile development */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0.3)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Mobile Development</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link
              className="detail-service-link new-serv-link"
              to="/andriod-details"
            >
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>04</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_mobile app.png"
              alt=""
            />
          </motion.div>
          {/* E-commers service */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0.4)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">E-commerce service</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link className="detail-service-link new-serv-link">
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>05</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_e commerce.png"
              alt=""
            />
          </motion.div>
          {/* work shops */}
          <motion.div
            initial="offscreen"
            whileInView={"onscreen"}
            variants={container(0.5)}
            className="services-each-single-card"
          >
            <h2 className="serv-h2">Workshops</h2>
            <p className="serv-para">
              Nullam tincidunt augue eget densis volu tpat, vitae ultri ces
              lectus and posuere. Duis urna lacus. READ MORE
            </p>
            <Link className="detail-service-link new-serv-link">
              <div className="all-services-each-card-button">
                <span>Read More</span>
                <span>
                  <FaAngleRight size={20} color="#fff" />
                </span>
              </div>
            </Link>
            {/* <span>06</span> */}
            <img
              className="services-each-single-card-image-card"
              src="/images/services_ workshop.png"
              alt=""
            />
          </motion.div>
        </div>
      </div>

      <div className="our-stories-second-card">
        <h2>
          Our <span className="shero-span-color">Quality</span> Management
        </h2>
        <p>
          Developing software that is of the finest excellence after extensive
          testing and optimization.
        </p>
        <p>
          With our solutions for QA testing, test automation, performance
          testing, and security testing, you can develop
        </p>
        <p>
          software that is of the highest caliber. Acquire a market edge over
          competitors.
        </p>
        <button>Nuhvin Quality</button>
      </div>
      {/*  */}
      <div className="our-stories-third-card-parents">
        <motion.div
          initial={{ x: -100 }}
          whileInView={{ x: 0 }}
          transition={transition}
          className="our-stories-third-card-parents-left-card"
        >
          <motion.span
            initial="offscreen"
            whileInView={"onscreen"}
            variants={featureVariantsAbout}
            // transition={{ duration: 18,  }}
          >
            <GiStarShuriken size={30} color="#fff" />
          </motion.span>
          <div className="our-stories-third-card-parents-left-first-images-card">
            <img src="/images/441bdc1e9b.jpg" alt="" />
          </div>
          <div className="our-stories-third-card-parents-left-second-images-card">
            <img src="/images/7f5ae780ce.jpg" alt="" />
            <div className="our-stories-third-card-parents-left-second-images-card-dotted-card">
              <span></span>
            </div>
          </div>
        </motion.div>
        <motion.div
          initial={{ x: 100 }}
          whileInView={{ x: 0 }}
          transition={{ ...transition, duration: 2 }}
          className="our-stories-third-card-parents-right-card"
        >
          <div className="our-stories-fisrt-card-our-story-text">
            {/* <span></span> */}
            <h3>FUTURE</h3>
          </div>
          <h1>
            The way we <span className="shero-span-color">work</span>
          </h1>
          <p>
            Our approach starts with creating authenticity through a thorough
            exploration call. We collaborate closely with our customers to
            better grasp their distinct vision, brand values, and mission.
          </p>
          <div className="our-stories-third-card-icons-with-text">
            <IoMdCheckmarkCircleOutline size={30} color="#ff3c00" />
            <span>
              <span>Collaborate with client every step of the way</span> :We
              collaborate extensively with our clients throughout the design
              process, allowing for comments and adjustments to ensure their
              satisfaction with the product.
            </span>
          </div>
          <div className="our-stories-third-card-icons-with-text">
            <IoMdCheckmarkCircleOutline size={30} color="#ff3c00" />
            <span>
              <span>Stay up-to-date with latest design trends</span>: We stay up
              with the most recent design trends so that we can provide our
              clients timeless, contemporary designs.
            </span>
          </div>
          <div className="our-stories-third-card-icons-with-text">
            <IoMdCheckmarkCircleOutline size={30} color="#ff3c00" />
            <span>
              <span>
                Provide designs of the highest caliber with short lead times.
              </span>
              : Our specialty is providing our clients with fast, high-quality
              designs so they may fulfill their deadlines and accomplish what
              they want to achieve.
            </span>
          </div>
          <div className="our-stories-third-card-icons-with-text">
            <IoMdCheckmarkCircleOutline size={30} color="#ff3c00" />
            <span>
              <span>Timeless</span> : It's relevant for the long term because it
              doesn't depend on specific technologies or trends.
            </span>
          </div>
          <div className="our-stories-third-card-icons-with-text">
            <IoMdCheckmarkCircleOutline size={30} color="#ff3c00" />
            <span>
              <span>Provide exceptional customer service</span> : We focus
              customer service and endeavour to give our clients a happy and
              stress-free experience.
            </span>
          </div>
        </motion.div>
      </div>
    </div>
  );
};
